# Generated by Django 5.1.6 on 2025-02-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_data',
            old_name='auth_id',
            new_name='auth',
        ),
    ]
