# Generated by Django 5.1.6 on 2025-02-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_rename_auth_id_employee_data_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
