# Generated by Django 5.1.6 on 2025-02-08 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_work_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_details', models.TextField(verbose_name='')),
                ('due_date', models.DateField(verbose_name='')),
                ('status', models.CharField(max_length=50, verbose_name='')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_data', to='superadmin.employee_data')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_data', to='superadmin.work_data')),
            ],
        ),
    ]
